/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cardboard_CardboardHelper */

#ifndef _Included_cardboard_CardboardHelper
#define _Included_cardboard_CardboardHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cardboard_CardboardHelper
 * Method:    getDisplayMetrics
 * Signature: ()Landroid/util/DisplayMetrics;
 */
JNIEXPORT jobject JNICALL Java_cardboard_CardboardHelper_getDisplayMetrics
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
